Fix exit codes in hotsync scripts
Print error messages and exit with error codes

diff --git a/root/usr/sbin/hotsync-promote b/root/usr/sbin/hotsync-promote
--- a/root/usr/sbin/hotsync-promote
+++ b/root/usr/sbin/hotsync-promote
@@ -33,13 +33,30 @@ sed -i 's/enabled = 0/enabled = 1/g' /etc/yum/pluginconf.d/nethserver_events.con
 
 /sbin/e-smith/restore-config
 
+if [[ $? == 0 ]]; then
+    echo "[NOTICE] Configuration restore completed!"
+else
+    echo "[ERROR] restore-config failed. Last error messages from /var/log/messages:  "
+    echo ""
+    grep -E '(ERROR|FAIL)' /var/log/messages | tail -15 | sed 's/^/    /'
+    echo ""
+    ((++exit_code))
+fi
+
 # Check if network roles need to be assigned
 flag=/var/run/.nethserver-fixnetwork
-echo "Configuration restore completed!"
 if [[ ! -f $flag ]]; then
     echo "To complete promotion to master, launch"
+    echo ""
+    echo "   /sbin/e-smith/signal-event post-restore-data"
+    echo ""
 else 
     echo "Go to Server Manager page \"Network\" and reassign roles to network interfaces"
     echo "and complete promotion to master by launching"
+    echo ""
+    echo "   /sbin/e-smith/signal-event post-restore-data"
+    echo ""
+    ((++exit_code))
 fi
-echo "   /sbin/e-smith/signal-event post-restore-data"
+
+exit ${exit_code}
diff --git a/root/usr/sbin/hotsync-slave b/root/usr/sbin/hotsync-slave
--- a/root/usr/sbin/hotsync-slave
+++ b/root/usr/sbin/hotsync-slave
@@ -26,6 +26,11 @@
 # launch reinstall action
 /etc/e-smith/events/actions/restore-config-reinstall
 
+if [[ $? != 0 ]]; then
+    echo "[ERROR] restore-config-reinstall failed!" 1>&2
+    exit 1
+fi
+
 # load configuration backup on interface if its md5 is equal to its md5file
 backupfile="/var/lib/nethserver/backup/backup-config.tar.xz"
 md5file="${backupfile}.md5"
